### ISSUE TITLE
file extension .a

### ISSUE THREAD

**Issue by natanael87** [aquaticsarah/libSU3#2]
I run comand 'make' and it has generated a file libSU3.a but I do not know how to use this for calculate the CGC for SU(3). Can you help me?

**Comment by psi-squared** [comment]
Hi, sorry for not replying for so long - I didn't have my notifications set up properly, so I only noticed this recently. Hopefully I've fixed that now.

I hope you were able to figure out how to use the library - if not, and it would still be useful to you, please let me know and I'll see if I can help :)

**Comment by natanael87** [comment]
Hi, thank you for your answer. I was able to make a static library libSU3.a, then I wrote a code using the library, but when I try to compile my program, it appears this error:

SU3.h:109:30: warning: explicit conversion operators only available with -std=c++11 or -std=gnu++11
     explicit operator double();

I don't know what it means, could you help me?

**Comment by natanael87** [comment]
I was able to compile the program!

Now, I've  just realized that I need to learn objects oriented program for using the SU3 library, isn't it?

**Comment by psi-squared** [comment]
Glad to hear you were able to compile it!

You shouldn't have to learn too much OO programming to use this - it does use C++ classes, but only quite lightly. Internally it does use classes quite a bit, but nothing fancy, and to just get the coefficients out you shouldn't need to deal with the internals.

For basic usage, there's a demo program showing how to generate the coefficients, how to loop over them, and how to fetch a particular coefficient:

https://github.com/psi-squared/libSU3/blob/master/progs/su3.cc

The functions of interest are probably do_rep() and print_isfs().

The only thing that doesn't demonstrate is doing arithmetic with the coefficients. But you can treat the 'sqrat' class like any other number type. Or you can convert the values to a 'double' and it'll work like anything else.

Please let me know if that helps :)

**Comment by natanael87** [comment]
Hi! you're right, do_rep() and print_isfs() are the function of interest.
I tried to use demo program to calculate (1,1)x(1,1) -> (2,2), but I couldn't figure out how.

This is what I wrote in terminal:
`g++ su3.cc -o su3ex2 libSU3.a -lgmpxx -lgmp -std=c++11`
`./su3ex2`
`./su3ex2 isf (1,1)x(1,1)->(2,2)`
but it appear me that:

bash: syntax error near unexpected token `('

**Comment by psi-squared** [comment]
You'll have to put the second argument in quotes, like this:

./su3ex2 isf "(1,1)x(1,1)->(2,2)"

I admit it's not the simplest thing to use, but hopefully that should help
